substitutions:
  _REGION: 'us-central1'
  _ARTIFACT_REGISTRY_HOST: 'LOCATION-docker.pkg.dev'
  _REPOSITORY: 'my-repo'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','${_ARTIFACT_REGISTRY_HOST}/$PROJECT_ID/${_REPOSITORY}/cool-fractal-thing:$SHORT_SHA','.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','${_ARTIFACT_REGISTRY_HOST}/$PROJECT_ID/${_REPOSITORY}/cool-fractal-thing:$SHORT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |-
    gcloud run deploy cool-fractal-thing \
      --image ${_ARTIFACT_REGISTRY_HOST}/$PROJECT_ID/${_REPOSITORY}/cool-fractal-thing:$SHORT_SHA \
      --region ${_REGION} \
      --platform managed \
      --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY
